/**
 * Shape of rows in our public.* tables (mirrors Supabase schema).
 * Hand-maintained for V0; replace with `supabase gen types typescript`
 * once the CLI is happily authed.
 */

export type DimensionId =
  | 'health'
  | 'strength'
  | 'mind'
  | 'wealth'
  | 'bonds'
  | 'craft';

/**
 * Sub-dimensions: 2 per dim. Tasks/skills can optionally point at one of
 * these for finer-grained organization (and per-sub subjective scoring).
 */
export type SubId =
  | 'sleep' | 'nutrition'
  | 'movement' | 'dexterity'
  | 'learn' | 'contemplate'
  | 'money' | 'career'
  | 'circle' | 'romance'
  | 'play' | 'build';

export type TaskType = 'one_shot' | 'daily' | 'weekly';

/**
 * Source of truth for when a task is "due". `task_type` is preserved as
 * a legacy hint but `recurrence` is what queries should consult.
 *
 * - one_shot: due once, ever. Disappears from "today" after first completion.
 * - daily: due every day. `target_count > 1` lets a single task be done
 *   multiple times per day (e.g. brush teeth 3x).
 * - weekly: due only on the listed weekdays (0=Sun, 6=Sat).
 * - monthly: due on the given day-of-month (skipped silently in months
 *   without that day, e.g. day=31 in February).
 */
export type Recurrence =
  | { type: 'one_shot' }
  | { type: 'daily' }
  | { type: 'weekly'; days: number[] }
  | { type: 'monthly'; day: number };

export type RecurrenceType = Recurrence['type'];

export interface Dimension {
  id: DimensionId;
  display_name: string;
  color: string;
  icon: string;
  sort_order: number;
}

export interface DimensionSub {
  id: SubId;
  dimension_id: DimensionId;
  display_name: string;
  icon: string;
  sort_order: number;
}

/**
 * Where a sub score came from. 'self' is the user's own gut rating,
 * 'questionnaire' is a derived score from the (future) onboarding quiz.
 */
export type AssessmentSource = 'self' | 'questionnaire';

export interface CharacterSubScore {
  character_id: string;
  source: AssessmentSource;
  sub_id: SubId;
  /** 0-5. */
  score: number;
  updated_at: string;
}

export interface AssessmentLogEntry {
  id: string;
  character_id: string;
  source: AssessmentSource;
  sub_id: SubId;
  score: number;
  recorded_at: string;
  /** Set when this row was generated by a questionnaire submission. NULL for
   * `source='self'` taps and any `source='questionnaire'` rows that predate
   * the session linkage. */
  session_id: string | null;
}

export interface QuestionnaireSession {
  id: string;
  character_id: string;
  taken_at: string;
  duration_seconds: number | null;
}

export interface QuestionnaireAnswerRow {
  id: string;
  session_id: string;
  question_id: string;
  raw_value: number;
}

export interface Profile {
  id: string;
  display_name: string;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface Character {
  id: string;
  total_xp: number;
  coins: number;
  created_at: string;
  updated_at: string;
}

export interface CharacterDimension {
  character_id: string;
  dimension_id: DimensionId;
  xp: number;
}

export type MetricType = 'reps' | 'minutes' | 'pages' | 'km' | 'ml' | 'custom';

export interface Task {
  id: string;
  character_id: string;
  title: string;
  description: string | null;
  difficulty: 1 | 2 | 3 | 4 | 5;
  task_type: TaskType;
  recurrence: Recurrence;
  target_count: number;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
  /**
   * Optional metric scaling — when set, the task's target value scales
   * with difficulty: base_value + increment_per_star * (difficulty - 1).
   * All four scaling fields are set together or all null.
   */
  metric_type: MetricType | null;
  metric_label: string | null;
  base_value: number | null;
  increment_per_star: number | null;
  /** NOT NULL after migration 0007 — every task lives under a sub. */
  sub_id: SubId;
}

export interface TaskTemplate {
  id: string;
  title: string;
  description: string | null;
  sub_id: SubId;
  difficulty: 1 | 2 | 3 | 4 | 5;
  task_type: TaskType;
  recurrence: Recurrence;
  target_count: number;
  metric_type: MetricType | null;
  metric_label: string | null;
  base_value: number | null;
  increment_per_star: number | null;
  sort_order: number;
}

/** Task with its linked dimensions (joined via task_dimension). */
export interface TaskWithDimensions extends Task {
  dimensions: DimensionId[];
}

export interface TaskCompletion {
  id: string;
  task_id: string;
  character_id: string;
  completed_at: string;
  xp_granted: number;
  coins_granted: number;
  /** Star difficulty actually used for this completion. */
  selected_difficulty: 1 | 2 | 3 | 4 | 5;
}

export type RewardCategory = 'indulgence' | 'good' | 'experience';

export interface Reward {
  id: string;
  character_id: string;
  title: string;
  description: string | null;
  cost: number;
  icon: string;
  category: RewardCategory;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

export interface RewardTemplate {
  id: string;
  title: string;
  description: string | null;
  cost: number;
  icon: string;
  category: RewardCategory;
  sort_order: number;
}

export interface RewardRedemption {
  id: string;
  reward_id: string;
  character_id: string;
  redeemed_at: string;
  cost_paid: number;
  /** NULL = banked (available to "Use"). Non-null = consumed at this time. */
  used_at: string | null;
}

export type TierName = 'beginner' | 'bronze' | 'silver' | 'gold' | 'master';

export interface Skill {
  id: string;
  display_name: string;
  unit: string;
  dimension_id: DimensionId;
  icon: string;
  sort_order: number;
  /** 1-3 sentence description shown on the skill detail screen. Catalog skills
   * may have this populated; user-created skills are optional. */
  description: string | null;
  /** Punchy 1-line population stat shown next to the medal — e.g. "Only 0.05%
   * of US adults finish a marathon (RunRepeat 2025)." Catalog only. */
  population_stat: string | null;
  /** NULL = catalog skill (visible to everyone). Non-null = owned by that
   * character (visible/editable only by them). */
  character_id: string | null;
  sub_id: SubId | null;
}

export interface SkillTier {
  id: string;
  skill_id: string;
  tier_name: TierName;
  threshold: number;
  sort_order: number;
  /** Optional plain-English description of what this tier means. */
  description: string | null;
  /** Optional 0-100 percentile of the adult population that achieves this
   * tier. Used to show "Top X%" subtext on tier badges. */
  percentile: number | null;
}

export interface SkillLog {
  id: string;
  character_id: string;
  skill_id: string;
  value: number;
  logged_at: string;
}

export interface SkillState {
  skill: Skill;
  tiers: SkillTier[];
  currentPr: number;
  lastLoggedAt: string | null;
  currentTier: SkillTier;
  nextTier: SkillTier | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Quests
// ─────────────────────────────────────────────────────────────────────────────

export type QuestStatus =
  | 'active'
  | 'completed'
  | 'failed'
  | 'expired'
  | 'abandoned';

export type QuestRequirementKind =
  | 'complete_task_n_times'
  | 'complete_any_in_dim'
  | 'reach_skill_value';

export interface Quest {
  id: string;
  character_id: string;
  template_id: string | null;
  title: string;
  description: string | null;
  started_at: string;
  deadline: string;
  reward_xp: number;
  reward_coins: number;
  allow_partial: boolean;
  status: QuestStatus;
  completed_at: string | null;
  created_at: string;
}

export interface QuestRequirement {
  id: string;
  quest_id: string;
  kind: QuestRequirementKind;
  task_id: string | null;
  dimension_id: DimensionId | null;
  skill_id: string | null;
  target_count: number | null;
  min_value: number | null;
  sort_order: number;
}

export interface QuestTemplate {
  id: string;
  title: string;
  description: string | null;
  category: string;
  suggested_duration_days: number;
  reward_xp: number;
  reward_coins: number;
  allow_partial: boolean;
  requirements: QuestTemplateRequirement[];
  sort_order: number;
}

export interface QuestTemplateRequirement {
  kind: QuestRequirementKind;
  task_title?: string;
  dimension_id?: DimensionId;
  skill_id?: string;
  target_count?: number;
  min_value?: number;
}

/** A quest enriched with its requirements + their current progress. */
export interface QuestWithProgress {
  quest: Quest;
  requirements: QuestRequirementWithProgress[];
  isComplete: boolean;
}

export interface QuestRequirementWithProgress {
  requirement: QuestRequirement;
  currentCount: number;
  isMet: boolean;
}
