-- ============================================================================
-- Psych — Big Five 120 (IPIP-NEO-style, autoral)
--
-- Seeds the `big_five_120` instrument: 5 traits × 6 facets × 4 items = 120.
--
-- Items are 100% authored in-house, inspired by the Big Five construct
-- definitions (Costa & McCrae / Goldberg). They do NOT reproduce any
-- copyrighted IPIP-NEO or NEO-PI-R item. We replicate the model's logic
-- (5 traits, 30 facets, sum-with-reverse scoring) without claiming the
-- "validated instrument" stamp.
--
-- Scoring (registered in migration 20260507000004):
--   - per leaf facet: sum(adjusted raw)         → [4, 20]
--   - per trait:      sum(facet sums)            → [24, 120]
-- Adjusted raw uses (6 - raw) on items where reverse_scored = true.
--
-- Approximately half of items per facet are reverse-scored (alternating)
-- to mitigate acquiescence bias.
-- ============================================================================

begin;

-- ─── 1. Instrument ─────────────────────────────────────────────────────────

insert into public.psych_instrument
  (id, name, description, category, version,
   item_count, scale_min, scale_max, scoring_doc_url,
   scoring_method, scale_labels)
values (
  'big_five_120',
  'Big Five — Perfil de 120 itens',
  'Inventário de 120 itens, autoral, inspirado no modelo Big Five ' ||
  '(5 traços × 6 facetas). Devolve um perfil multidimensional, não um ' ||
  'tipo único. Não substitui instrumento clínico.',
  'self_knowledge', '1.0', 120, 1, 5,
  'docs/psych-instruments-v1.md#52-ipip-neo-120-big-five',
  'big_five_sum',
  '{
    "pt": [
      {"label": "Discordo totalmente", "value": 1},
      {"label": "Discordo",            "value": 2},
      {"label": "Neutro",              "value": 3},
      {"label": "Concordo",            "value": 4},
      {"label": "Concordo totalmente", "value": 5}
    ],
    "en": [
      {"label": "Strongly disagree",   "value": 1},
      {"label": "Disagree",            "value": 2},
      {"label": "Neutral",             "value": 3},
      {"label": "Agree",               "value": 4},
      {"label": "Strongly agree",      "value": 5}
    ]
  }'::jsonb
);

-- ─── 2. Traits (parent facets) ─────────────────────────────────────────────

insert into public.psych_facet
  (id, instrument_id, parent_facet_id, slug, name, description, position)
values
  ('big_five:trait:openness',          'big_five_120', null,
   'openness',          'Abertura',
   'Curiosidade intelectual, gosto pelo novo, profundidade emocional, '
   'apreciação de arte e ideias.',
   1000),
  ('big_five:trait:conscientiousness', 'big_five_120', null,
   'conscientiousness', 'Conscienciosidade',
   'Organização, disciplina, foco em metas, senso de dever, persistência.',
   2000),
  ('big_five:trait:extraversion',      'big_five_120', null,
   'extraversion',      'Extroversão',
   'Energia social, busca por estímulo, assertividade, expressividade emocional.',
   3000),
  ('big_five:trait:agreeableness',     'big_five_120', null,
   'agreeableness',     'Amabilidade',
   'Cooperação, empatia, confiança nos outros, evita confrontação.',
   4000),
  ('big_five:trait:neuroticism',       'big_five_120', null,
   'neuroticism',       'Neuroticismo',
   'Tendência a emoções negativas (ansiedade, raiva, tristeza), '
   'sensibilidade ao estresse.',
   5000);

-- ─── 3. Facets (30 children) ───────────────────────────────────────────────

insert into public.psych_facet
  (id, instrument_id, parent_facet_id, slug, name, position)
values
  -- Openness
  ('big_five:facet:openness:imagination',
   'big_five_120', 'big_five:trait:openness',
   'imagination',          'Imaginação',          1010),
  ('big_five:facet:openness:artistic_interests',
   'big_five_120', 'big_five:trait:openness',
   'artistic_interests',   'Interesse Artístico', 1020),
  ('big_five:facet:openness:emotionality',
   'big_five_120', 'big_five:trait:openness',
   'emotionality',         'Emocionalidade',      1030),
  ('big_five:facet:openness:adventurousness',
   'big_five_120', 'big_five:trait:openness',
   'adventurousness',      'Aventura',            1040),
  ('big_five:facet:openness:intellect',
   'big_five_120', 'big_five:trait:openness',
   'intellect',            'Intelecto',           1050),
  ('big_five:facet:openness:liberalism',
   'big_five_120', 'big_five:trait:openness',
   'liberalism',           'Liberalismo',         1060),
  -- Conscientiousness
  ('big_five:facet:conscientiousness:self_efficacy',
   'big_five_120', 'big_five:trait:conscientiousness',
   'self_efficacy',        'Auto-eficácia',       2010),
  ('big_five:facet:conscientiousness:orderliness',
   'big_five_120', 'big_five:trait:conscientiousness',
   'orderliness',          'Organização',         2020),
  ('big_five:facet:conscientiousness:dutifulness',
   'big_five_120', 'big_five:trait:conscientiousness',
   'dutifulness',          'Senso de Dever',      2030),
  ('big_five:facet:conscientiousness:achievement_striving',
   'big_five_120', 'big_five:trait:conscientiousness',
   'achievement_striving', 'Foco em Realização',  2040),
  ('big_five:facet:conscientiousness:self_discipline',
   'big_five_120', 'big_five:trait:conscientiousness',
   'self_discipline',      'Autodisciplina',      2050),
  ('big_five:facet:conscientiousness:cautiousness',
   'big_five_120', 'big_five:trait:conscientiousness',
   'cautiousness',         'Cautela',             2060),
  -- Extraversion
  ('big_five:facet:extraversion:friendliness',
   'big_five_120', 'big_five:trait:extraversion',
   'friendliness',         'Cordialidade',        3010),
  ('big_five:facet:extraversion:gregariousness',
   'big_five_120', 'big_five:trait:extraversion',
   'gregariousness',       'Sociabilidade',       3020),
  ('big_five:facet:extraversion:assertiveness',
   'big_five_120', 'big_five:trait:extraversion',
   'assertiveness',        'Assertividade',       3030),
  ('big_five:facet:extraversion:activity_level',
   'big_five_120', 'big_five:trait:extraversion',
   'activity_level',       'Nível de Atividade',  3040),
  ('big_five:facet:extraversion:excitement_seeking',
   'big_five_120', 'big_five:trait:extraversion',
   'excitement_seeking',   'Busca por Estímulo',  3050),
  ('big_five:facet:extraversion:cheerfulness',
   'big_five_120', 'big_five:trait:extraversion',
   'cheerfulness',         'Alegria',             3060),
  -- Agreeableness
  ('big_five:facet:agreeableness:trust',
   'big_five_120', 'big_five:trait:agreeableness',
   'trust',                'Confiança',           4010),
  ('big_five:facet:agreeableness:morality',
   'big_five_120', 'big_five:trait:agreeableness',
   'morality',             'Sinceridade',         4020),
  ('big_five:facet:agreeableness:altruism',
   'big_five_120', 'big_five:trait:agreeableness',
   'altruism',             'Altruísmo',           4030),
  ('big_five:facet:agreeableness:cooperation',
   'big_five_120', 'big_five:trait:agreeableness',
   'cooperation',          'Cooperação',          4040),
  ('big_five:facet:agreeableness:modesty',
   'big_five_120', 'big_five:trait:agreeableness',
   'modesty',              'Modéstia',            4050),
  ('big_five:facet:agreeableness:sympathy',
   'big_five_120', 'big_five:trait:agreeableness',
   'sympathy',             'Empatia',             4060),
  -- Neuroticism
  ('big_five:facet:neuroticism:anxiety',
   'big_five_120', 'big_five:trait:neuroticism',
   'anxiety',              'Ansiedade',           5010),
  ('big_five:facet:neuroticism:anger',
   'big_five_120', 'big_five:trait:neuroticism',
   'anger',                'Raiva',               5020),
  ('big_five:facet:neuroticism:depression',
   'big_five_120', 'big_five:trait:neuroticism',
   'depression',           'Tristeza',            5030),
  ('big_five:facet:neuroticism:self_consciousness',
   'big_five_120', 'big_five:trait:neuroticism',
   'self_consciousness',   'Auto-Consciência',    5040),
  ('big_five:facet:neuroticism:immoderation',
   'big_five_120', 'big_five:trait:neuroticism',
   'immoderation',         'Impulsividade',       5050),
  ('big_five:facet:neuroticism:vulnerability',
   'big_five_120', 'big_five:trait:neuroticism',
   'vulnerability',        'Vulnerabilidade',     5060);

-- ─── 4. Items (120) ────────────────────────────────────────────────────────
-- Items are authored. Format: 4 per facet, alternating forward/reverse so
-- about half the pool is reverse-scored. options_jsonb is null — items
-- inherit the instrument's scale_labels (uniform Likert 1..5).

insert into public.psych_item
  (id, instrument_id, facet_id, position, text_pt, text_en,
   reverse_scored, options_jsonb)
values
  -- ───────────── Openness ─────────────
  -- Imagination
  ('bf_o_imag_1', 'big_five_120', 'big_five:facet:openness:imagination', 1,
   'Eu mergulho fácil em devaneios e mundos imaginários.',
   'I get lost in daydreams and imagined worlds easily.',
   false, null),
  ('bf_o_imag_2', 'big_five_120', 'big_five:facet:openness:imagination', 2,
   'Tenho uma vida interior intensa que poucas pessoas conhecem.',
   'I have a vivid inner life that few people see.',
   false, null),
  ('bf_o_imag_3', 'big_five_120', 'big_five:facet:openness:imagination', 3,
   'Prefiro pensar em coisas concretas a divagar.',
   'I''d rather focus on concrete things than let my mind wander.',
   true, null),
  ('bf_o_imag_4', 'big_five_120', 'big_five:facet:openness:imagination', 4,
   'Imaginar cenários hipotéticos me parece perda de tempo.',
   'Imagining hypothetical scenarios feels like a waste of time to me.',
   true, null),
  -- Artistic Interests
  ('bf_o_arts_1', 'big_five_120', 'big_five:facet:openness:artistic_interests', 5,
   'Pinturas, fotos ou paisagens conseguem me parar de verdade.',
   'A painting, photograph or landscape can stop me in my tracks.',
   false, null),
  ('bf_o_arts_2', 'big_five_120', 'big_five:facet:openness:artistic_interests', 6,
   'Faço questão de buscar arte, música ou literatura que me toque.',
   'I actively seek out art, music or writing that moves me.',
   false, null),
  ('bf_o_arts_3', 'big_five_120', 'big_five:facet:openness:artistic_interests', 7,
   'Não vejo muita graça em galerias ou museus.',
   'I don''t see much point in galleries or museums.',
   true, null),
  ('bf_o_arts_4', 'big_five_120', 'big_five:facet:openness:artistic_interests', 8,
   'Pra mim, arte é decoração — funcional, no máximo.',
   'Art is decoration to me — functional, at best.',
   true, null),
  -- Emotionality
  ('bf_o_emot_1', 'big_five_120', 'big_five:facet:openness:emotionality', 9,
   'Sinto minhas emoções de forma intensa, mesmo as sutis.',
   'I feel my emotions intensely, even the subtle ones.',
   false, null),
  ('bf_o_emot_2', 'big_five_120', 'big_five:facet:openness:emotionality', 10,
   'Consigo nomear com clareza o que estou sentindo no momento.',
   'I can clearly name what I''m feeling in the moment.',
   false, null),
  ('bf_o_emot_3', 'big_five_120', 'big_five:facet:openness:emotionality', 11,
   'Raramente paro pra notar como estou me sentindo.',
   'I rarely stop to notice how I''m feeling.',
   true, null),
  ('bf_o_emot_4', 'big_five_120', 'big_five:facet:openness:emotionality', 12,
   'Emoções tendem a passar por mim sem deixar marca.',
   'Emotions tend to pass through me without leaving much of a mark.',
   true, null),
  -- Adventurousness
  ('bf_o_advt_1', 'big_five_120', 'big_five:facet:openness:adventurousness', 13,
   'Curto experimentar comidas, lugares ou rotas que nunca tentei.',
   'I enjoy trying foods, places or routes I''ve never tried before.',
   false, null),
  ('bf_o_advt_2', 'big_five_120', 'big_five:facet:openness:adventurousness', 14,
   'Mudar a rotina é estímulo, não estresse.',
   'Changing my routine is stimulating, not stressful.',
   false, null),
  ('bf_o_advt_3', 'big_five_120', 'big_five:facet:openness:adventurousness', 15,
   'Prefiro o que já conheço — o novo cansa.',
   'I prefer the familiar — novelty wears me down.',
   true, null),
  ('bf_o_advt_4', 'big_five_120', 'big_five:facet:openness:adventurousness', 16,
   'Costumo pedir o mesmo prato no mesmo restaurante.',
   'I tend to order the same dish at the same restaurant.',
   true, null),
  -- Intellect
  ('bf_o_intl_1', 'big_five_120', 'big_five:facet:openness:intellect', 17,
   'Curto debater ideias abstratas mesmo sem aplicação prática.',
   'I enjoy debating abstract ideas even without practical use.',
   false, null),
  ('bf_o_intl_2', 'big_five_120', 'big_five:facet:openness:intellect', 18,
   'Conceitos teóricos ou filosóficos prendem minha atenção.',
   'Theoretical or philosophical concepts hold my attention.',
   false, null),
  ('bf_o_intl_3', 'big_five_120', 'big_five:facet:openness:intellect', 19,
   'Conversa muito teórica me dá sono.',
   'Heavy theoretical conversation makes me sleepy.',
   true, null),
  ('bf_o_intl_4', 'big_five_120', 'big_five:facet:openness:intellect', 20,
   'Prefiro lidar com fatos concretos a ficar especulando.',
   'I''d rather deal with concrete facts than speculate.',
   true, null),
  -- Liberalism
  ('bf_o_libr_1', 'big_five_120', 'big_five:facet:openness:liberalism', 21,
   'Costumo questionar costumes só porque "sempre foi assim".',
   'I question customs that exist only because "it''s always been this way."',
   false, null),
  ('bf_o_libr_2', 'big_five_120', 'big_five:facet:openness:liberalism', 22,
   'Acho que muita coisa que se chama tradição precisa ser reinventada.',
   'A lot of what people call tradition needs reinventing.',
   false, null),
  ('bf_o_libr_3', 'big_five_120', 'big_five:facet:openness:liberalism', 23,
   'Tradições e regras estabelecidas existem por uma razão.',
   'Established traditions and rules exist for a reason.',
   true, null),
  ('bf_o_libr_4', 'big_five_120', 'big_five:facet:openness:liberalism', 24,
   'Costumo seguir o que a maioria já validou.',
   'I tend to go with what the majority has already validated.',
   true, null),

  -- ───────────── Conscientiousness ─────────────
  -- Self-Efficacy
  ('bf_c_seff_1', 'big_five_120', 'big_five:facet:conscientiousness:self_efficacy', 25,
   'Encaro tarefas difíceis confiando que vou dar conta.',
   'I tackle hard tasks trusting I''ll figure them out.',
   false, null),
  ('bf_c_seff_2', 'big_five_120', 'big_five:facet:conscientiousness:self_efficacy', 26,
   'Quando assumo um compromisso, sei que vou entregar.',
   'When I commit to something, I know I''ll deliver.',
   false, null),
  ('bf_c_seff_3', 'big_five_120', 'big_five:facet:conscientiousness:self_efficacy', 27,
   'Costumo duvidar se vou conseguir terminar o que começo.',
   'I often doubt I''ll finish what I start.',
   true, null),
  ('bf_c_seff_4', 'big_five_120', 'big_five:facet:conscientiousness:self_efficacy', 28,
   'Me sinto despreparado pra maioria dos desafios novos.',
   'I feel underprepared for most new challenges.',
   true, null),
  -- Orderliness
  ('bf_c_ordr_1', 'big_five_120', 'big_five:facet:conscientiousness:orderliness', 29,
   'Mantenho meu espaço de trabalho organizado por padrão.',
   'I keep my workspace organized by default.',
   false, null),
  ('bf_c_ordr_2', 'big_five_120', 'big_five:facet:conscientiousness:orderliness', 30,
   'Gosto de ter tudo no lugar antes de começar uma tarefa.',
   'I like having everything in place before I start a task.',
   false, null),
  ('bf_c_ordr_3', 'big_five_120', 'big_five:facet:conscientiousness:orderliness', 31,
   'Costumo trabalhar em meio a uma boa bagunça.',
   'I tend to work amid solid chaos.',
   true, null),
  ('bf_c_ordr_4', 'big_five_120', 'big_five:facet:conscientiousness:orderliness', 32,
   'Sistemas e checklists me sufocam mais do que ajudam.',
   'Systems and checklists smother me more than they help.',
   true, null),
  -- Dutifulness
  ('bf_c_duty_1', 'big_five_120', 'big_five:facet:conscientiousness:dutifulness', 33,
   'Cumpro minha palavra mesmo quando voltar atrás seria mais fácil.',
   'I keep my word even when going back on it would be easier.',
   false, null),
  ('bf_c_duty_2', 'big_five_120', 'big_five:facet:conscientiousness:dutifulness', 34,
   'Levo a sério promessas que faço — pra mim e pros outros.',
   'I take promises seriously, the ones I make to others and to myself.',
   false, null),
  ('bf_c_duty_3', 'big_five_120', 'big_five:facet:conscientiousness:dutifulness', 35,
   'Compromissos pequenos eu posso furar sem grande problema.',
   'Small commitments I can blow off without much issue.',
   true, null),
  ('bf_c_duty_4', 'big_five_120', 'big_five:facet:conscientiousness:dutifulness', 36,
   'Promessas são mais intenções do que obrigações.',
   'Promises are more intentions than obligations.',
   true, null),
  -- Achievement-Striving
  ('bf_c_achv_1', 'big_five_120', 'big_five:facet:conscientiousness:achievement_striving', 37,
   'Tenho metas ambiciosas e me cobro pra alcançar.',
   'I set ambitious goals and push myself toward them.',
   false, null),
  ('bf_c_achv_2', 'big_five_120', 'big_five:facet:conscientiousness:achievement_striving', 38,
   'Não me contento com "bom o suficiente" no que faço.',
   '"Good enough" doesn''t satisfy me in my work.',
   false, null),
  ('bf_c_achv_3', 'big_five_120', 'big_five:facet:conscientiousness:achievement_striving', 39,
   'Prefiro entregar o suficiente e tocar a vida.',
   'I''d rather deliver enough and move on with life.',
   true, null),
  ('bf_c_achv_4', 'big_five_120', 'big_five:facet:conscientiousness:achievement_striving', 40,
   'Ambição me parece esforço desnecessário.',
   'Ambition strikes me as unnecessary effort.',
   true, null),
  -- Self-Discipline
  ('bf_c_disc_1', 'big_five_120', 'big_five:facet:conscientiousness:self_discipline', 41,
   'Continuo no plano mesmo quando perdi a vontade.',
   'I stick to the plan even when motivation has left.',
   false, null),
  ('bf_c_disc_2', 'big_five_120', 'big_five:facet:conscientiousness:self_discipline', 42,
   'Termino o que começo, mesmo nas tarefas chatas.',
   'I finish what I start, even the boring tasks.',
   false, null),
  ('bf_c_disc_3', 'big_five_120', 'big_five:facet:conscientiousness:self_discipline', 43,
   'Quando algo fica chato, costumo sair fora.',
   'When something gets boring, I tend to drop it.',
   true, null),
  ('bf_c_disc_4', 'big_five_120', 'big_five:facet:conscientiousness:self_discipline', 44,
   'Procrastinação é meu padrão, não a exceção.',
   'Procrastination is my default, not the exception.',
   true, null),
  -- Cautiousness
  ('bf_c_caut_1', 'big_five_120', 'big_five:facet:conscientiousness:cautiousness', 45,
   'Penso bastante antes de tomar decisões importantes.',
   'I think a lot before making important decisions.',
   false, null),
  ('bf_c_caut_2', 'big_five_120', 'big_five:facet:conscientiousness:cautiousness', 46,
   'Considero as consequências antes de agir por impulso.',
   'I weigh consequences before acting on impulse.',
   false, null),
  ('bf_c_caut_3', 'big_five_120', 'big_five:facet:conscientiousness:cautiousness', 47,
   'Costumo decidir rápido e ver no que dá.',
   'I tend to decide fast and see how it plays out.',
   true, null),
  ('bf_c_caut_4', 'big_five_120', 'big_five:facet:conscientiousness:cautiousness', 48,
   'Já tomei decisões de que me arrependo por não ter pensado direito.',
   'I''ve made decisions I regret because I didn''t think them through.',
   true, null),

  -- ───────────── Extraversion ─────────────
  -- Friendliness
  ('bf_e_frnd_1', 'big_five_120', 'big_five:facet:extraversion:friendliness', 49,
   'Fico genuinamente feliz em ver pessoas que conheço.',
   'I''m genuinely glad to see people I know.',
   false, null),
  ('bf_e_frnd_2', 'big_five_120', 'big_five:facet:extraversion:friendliness', 50,
   'Demonstro afeto sem dificuldade pelas pessoas próximas.',
   'I show affection toward people close to me without hesitation.',
   false, null),
  ('bf_e_frnd_3', 'big_five_120', 'big_five:facet:extraversion:friendliness', 51,
   'Mantenho uma certa distância mesmo com gente que conheço bem.',
   'I keep a certain distance even with people I know well.',
   true, null),
  ('bf_e_frnd_4', 'big_five_120', 'big_five:facet:extraversion:friendliness', 52,
   'Demonstrar carinho me deixa desconfortável.',
   'Showing affection makes me uncomfortable.',
   true, null),
  -- Gregariousness
  ('bf_e_greg_1', 'big_five_120', 'big_five:facet:extraversion:gregariousness', 53,
   'Prefiro estar com pessoas a estar sozinho.',
   'I''d rather be with people than alone.',
   false, null),
  ('bf_e_greg_2', 'big_five_120', 'big_five:facet:extraversion:gregariousness', 54,
   'Festas e eventos cheios me energizam.',
   'Parties and crowded events energize me.',
   false, null),
  ('bf_e_greg_3', 'big_five_120', 'big_five:facet:extraversion:gregariousness', 55,
   'Multidões me esgotam rapidamente.',
   'Crowds drain me quickly.',
   true, null),
  ('bf_e_greg_4', 'big_five_120', 'big_five:facet:extraversion:gregariousness', 56,
   'Saio do meu caminho pra evitar eventos sociais grandes.',
   'I go out of my way to avoid big social events.',
   true, null),
  -- Assertiveness
  ('bf_e_asrt_1', 'big_five_120', 'big_five:facet:extraversion:assertiveness', 57,
   'Em grupo, costumo assumir a liderança naturalmente.',
   'In a group, I tend to take the lead naturally.',
   false, null),
  ('bf_e_asrt_2', 'big_five_120', 'big_five:facet:extraversion:assertiveness', 58,
   'Falo o que penso sem ficar adoçando.',
   'I say what I think without sugarcoating it.',
   false, null),
  ('bf_e_asrt_3', 'big_five_120', 'big_five:facet:extraversion:assertiveness', 59,
   'Prefiro deixar outros tomarem a frente.',
   'I''d rather let others take the lead.',
   true, null),
  ('bf_e_asrt_4', 'big_five_120', 'big_five:facet:extraversion:assertiveness', 60,
   'Tenho dificuldade de me impor quando alguém me passa por cima.',
   'I struggle to push back when someone walks over me.',
   true, null),
  -- Activity Level
  ('bf_e_actv_1', 'big_five_120', 'big_five:facet:extraversion:activity_level', 61,
   'Mantenho um ritmo intenso na maior parte do dia.',
   'I keep an intense pace most of the day.',
   false, null),
  ('bf_e_actv_2', 'big_five_120', 'big_five:facet:extraversion:activity_level', 62,
   'Lido bem com várias coisas acontecendo ao mesmo tempo.',
   'I handle multiple things happening at once well.',
   false, null),
  ('bf_e_actv_3', 'big_five_120', 'big_five:facet:extraversion:activity_level', 63,
   'Prefiro um ritmo calmo e poucas coisas em paralelo.',
   'I prefer a calm pace with few things in parallel.',
   true, null),
  ('bf_e_actv_4', 'big_five_120', 'big_five:facet:extraversion:activity_level', 64,
   'Ficar parado, fazendo nada, é tão bom quanto produzir.',
   'Sitting still doing nothing is as good as being productive.',
   true, null),
  -- Excitement-Seeking
  ('bf_e_exct_1', 'big_five_120', 'big_five:facet:extraversion:excitement_seeking', 65,
   'Curto experiências intensas — adrenalina, viagens duras, esportes radicais.',
   'I enjoy intense experiences — adrenaline, rough travel, extreme sports.',
   false, null),
  ('bf_e_exct_2', 'big_five_120', 'big_five:facet:extraversion:excitement_seeking', 66,
   'Me chateia quando os dias ficam previsíveis demais.',
   'Predictable days bore me.',
   false, null),
  ('bf_e_exct_3', 'big_five_120', 'big_five:facet:extraversion:excitement_seeking', 67,
   'Tranquilidade vale mais que adrenalina pra mim.',
   'Calm is worth more than thrills to me.',
   true, null),
  ('bf_e_exct_4', 'big_five_120', 'big_five:facet:extraversion:excitement_seeking', 68,
   'Evito situações que prometem muita emoção forte.',
   'I avoid situations that promise too much intense emotion.',
   true, null),
  -- Cheerfulness
  ('bf_e_chrf_1', 'big_five_120', 'big_five:facet:extraversion:cheerfulness', 69,
   'Sou de bom humor por padrão.',
   'I''m in a good mood by default.',
   false, null),
  ('bf_e_chrf_2', 'big_five_120', 'big_five:facet:extraversion:cheerfulness', 70,
   'Me pego rindo ou sorrindo várias vezes ao longo do dia.',
   'I catch myself laughing or smiling several times a day.',
   false, null),
  ('bf_e_chrf_3', 'big_five_120', 'big_five:facet:extraversion:cheerfulness', 71,
   'Bom humor é exceção, não regra, no meu dia.',
   'Good mood is the exception, not the rule, in my day.',
   true, null),
  ('bf_e_chrf_4', 'big_five_120', 'big_five:facet:extraversion:cheerfulness', 72,
   'Custa um esforço pra eu chegar num estado animado.',
   'It takes effort for me to reach a cheerful state.',
   true, null),

  -- ───────────── Agreeableness ─────────────
  -- Trust
  ('bf_a_trst_1', 'big_five_120', 'big_five:facet:agreeableness:trust', 73,
   'Parto do princípio que as pessoas têm boa intenção.',
   'I assume people have good intentions.',
   false, null),
  ('bf_a_trst_2', 'big_five_120', 'big_five:facet:agreeableness:trust', 74,
   'Confio nos outros até ter motivo concreto pra desconfiar.',
   'I trust people until I have concrete reason to distrust them.',
   false, null),
  ('bf_a_trst_3', 'big_five_120', 'big_five:facet:agreeableness:trust', 75,
   'Costumo desconfiar das motivações alheias.',
   'I tend to be suspicious of others'' motives.',
   true, null),
  ('bf_a_trst_4', 'big_five_120', 'big_five:facet:agreeableness:trust', 76,
   'Já me decepcionei demais pra confiar fácil.',
   'I''ve been disappointed too many times to trust easily.',
   true, null),
  -- Morality (sincerity, no manipulation)
  ('bf_a_mrlt_1', 'big_five_120', 'big_five:facet:agreeableness:morality', 77,
   'Falo a verdade mesmo quando convém maquiar.',
   'I tell the truth even when shading it would be convenient.',
   false, null),
  ('bf_a_mrlt_2', 'big_five_120', 'big_five:facet:agreeableness:morality', 78,
   'Não uso pessoas pra conseguir o que quero.',
   'I don''t use people to get what I want.',
   false, null),
  ('bf_a_mrlt_3', 'big_five_120', 'big_five:facet:agreeableness:morality', 79,
   'Em alguns contextos, manipular um pouco é necessário.',
   'In some contexts, a little manipulation is necessary.',
   true, null),
  ('bf_a_mrlt_4', 'big_five_120', 'big_five:facet:agreeableness:morality', 80,
   'Tenho talento pra falar o que cada um quer ouvir.',
   'I have a talent for telling each person what they want to hear.',
   true, null),
  -- Altruism
  ('bf_a_altr_1', 'big_five_120', 'big_five:facet:agreeableness:altruism', 81,
   'Costumo me oferecer pra ajudar mesmo sem ninguém pedir.',
   'I tend to offer help even when no one asked.',
   false, null),
  ('bf_a_altr_2', 'big_five_120', 'big_five:facet:agreeableness:altruism', 82,
   'Sinto satisfação real em fazer algo bom pelos outros.',
   'I feel real satisfaction in doing good for others.',
   false, null),
  ('bf_a_altr_3', 'big_five_120', 'big_five:facet:agreeableness:altruism', 83,
   'Cada um cuida do que é seu — não é meu papel salvar ninguém.',
   'Each person handles their own — saving anyone isn''t my job.',
   true, null),
  ('bf_a_altr_4', 'big_five_120', 'big_five:facet:agreeableness:altruism', 84,
   'Ajudar os outros me cansa mais do que recompensa.',
   'Helping others drains me more than it rewards me.',
   true, null),
  -- Cooperation (dislike of confrontation)
  ('bf_a_coop_1', 'big_five_120', 'big_five:facet:agreeableness:cooperation', 85,
   'Cedo em discussões pequenas pra manter a paz.',
   'I give in on small disputes to keep the peace.',
   false, null),
  ('bf_a_coop_2', 'big_five_120', 'big_five:facet:agreeableness:cooperation', 86,
   'Prefiro buscar consenso a vencer um argumento.',
   'I''d rather find consensus than win an argument.',
   false, null),
  ('bf_a_coop_3', 'big_five_120', 'big_five:facet:agreeableness:cooperation', 87,
   'Discussão não me incomoda — pode esquentar que sigo firme.',
   'Conflict doesn''t bother me — let it heat up, I stay firm.',
   true, null),
  ('bf_a_coop_4', 'big_five_120', 'big_five:facet:agreeableness:cooperation', 88,
   'Quando estou certo, defendo minha posição até o fim.',
   'When I''m right, I defend my position to the end.',
   true, null),
  -- Modesty
  ('bf_a_mdty_1', 'big_five_120', 'big_five:facet:agreeableness:modesty', 89,
   'Evito puxar atenção pras minhas conquistas.',
   'I avoid pulling attention to my accomplishments.',
   false, null),
  ('bf_a_mdty_2', 'big_five_120', 'big_five:facet:agreeableness:modesty', 90,
   'Me sinto desconfortável quando me elogiam demais.',
   'I feel uncomfortable when I''m praised too much.',
   false, null),
  ('bf_a_mdty_3', 'big_five_120', 'big_five:facet:agreeableness:modesty', 91,
   'Quando faço algo bom, faço questão que saibam.',
   'When I do something well, I make sure people know.',
   true, null),
  ('bf_a_mdty_4', 'big_five_120', 'big_five:facet:agreeableness:modesty', 92,
   'Sei que sou melhor que a média em várias coisas.',
   'I know I''m better than average at several things.',
   true, null),
  -- Sympathy
  ('bf_a_symp_1', 'big_five_120', 'big_five:facet:agreeableness:sympathy', 93,
   'Me comovo facilmente quando vejo alguém sofrendo.',
   'I''m easily moved when I see someone suffering.',
   false, null),
  ('bf_a_symp_2', 'big_five_120', 'big_five:facet:agreeableness:sympathy', 94,
   'Carrego junto a dor de quem é próximo de mim.',
   'I carry the pain of those close to me along with them.',
   false, null),
  ('bf_a_symp_3', 'big_five_120', 'big_five:facet:agreeableness:sympathy', 95,
   'Mantenho a cabeça fria mesmo diante de uma história triste.',
   'I keep a cool head even faced with a sad story.',
   true, null),
  ('bf_a_symp_4', 'big_five_120', 'big_five:facet:agreeableness:sympathy', 96,
   'Sentimento alheio é problema do dono.',
   'Other people''s feelings are their owner''s problem.',
   true, null),

  -- ───────────── Neuroticism ─────────────
  -- Anxiety
  ('bf_n_anxy_1', 'big_five_120', 'big_five:facet:neuroticism:anxiety', 97,
   'Me pego antecipando problemas que talvez nunca aconteçam.',
   'I catch myself anticipating problems that may never happen.',
   false, null),
  ('bf_n_anxy_2', 'big_five_120', 'big_five:facet:neuroticism:anxiety', 98,
   'Tensão e preocupação fazem parte do meu dia.',
   'Tension and worry are part of my day.',
   false, null),
  ('bf_n_anxy_3', 'big_five_120', 'big_five:facet:neuroticism:anxiety', 99,
   'Não sou de me preocupar com cenários hipotéticos.',
   'I''m not one to worry about hypothetical scenarios.',
   true, null),
  ('bf_n_anxy_4', 'big_five_120', 'big_five:facet:neuroticism:anxiety', 100,
   'Mantenho a calma diante de imprevistos.',
   'I stay calm when surprises hit.',
   true, null),
  -- Anger
  ('bf_n_angr_1', 'big_five_120', 'big_five:facet:neuroticism:anger', 101,
   'Pequenas coisas me irritam mais do que deveriam.',
   'Small things irritate me more than they should.',
   false, null),
  ('bf_n_angr_2', 'big_five_120', 'big_five:facet:neuroticism:anger', 102,
   'Quando algo dá errado, costumo perder a paciência rápido.',
   'When something goes wrong, I tend to lose patience fast.',
   false, null),
  ('bf_n_angr_3', 'big_five_120', 'big_five:facet:neuroticism:anger', 103,
   'Custa muito pra alguma coisa me tirar do sério.',
   'It takes a lot to get under my skin.',
   true, null),
  ('bf_n_angr_4', 'big_five_120', 'big_five:facet:neuroticism:anger', 104,
   'Frustração escorre por mim sem virar raiva.',
   'Frustration slides off me without turning into anger.',
   true, null),
  -- Depression (sadness frequency)
  ('bf_n_depr_1', 'big_five_120', 'big_five:facet:neuroticism:depression', 105,
   'Tenho fases de desânimo que duram dias sem motivo claro.',
   'I have stretches of low mood that last days for no clear reason.',
   false, null),
  ('bf_n_depr_2', 'big_five_120', 'big_five:facet:neuroticism:depression', 106,
   'Pensamentos pesados me visitam com frequência.',
   'Heavy thoughts visit me often.',
   false, null),
  ('bf_n_depr_3', 'big_five_120', 'big_five:facet:neuroticism:depression', 107,
   'Mantenho um humor estável a maior parte do tempo.',
   'I keep a steady mood most of the time.',
   true, null),
  ('bf_n_depr_4', 'big_five_120', 'big_five:facet:neuroticism:depression', 108,
   'Tristeza profunda é raridade na minha vida.',
   'Deep sadness is rare in my life.',
   true, null),
  -- Self-Consciousness
  ('bf_n_slfc_1', 'big_five_120', 'big_five:facet:neuroticism:self_consciousness', 109,
   'Fico desconfortável quando viro o foco da atenção.',
   'I get uncomfortable when I''m the center of attention.',
   false, null),
  ('bf_n_slfc_2', 'big_five_120', 'big_five:facet:neuroticism:self_consciousness', 110,
   'Me preocupo bastante com o que os outros estão pensando de mim.',
   'I worry a lot about what others are thinking of me.',
   false, null),
  ('bf_n_slfc_3', 'big_five_120', 'big_five:facet:neuroticism:self_consciousness', 111,
   'Pouco me importa o julgamento alheio.',
   'I care little about other people''s judgment.',
   true, null),
  ('bf_n_slfc_4', 'big_five_120', 'big_five:facet:neuroticism:self_consciousness', 112,
   'Falar em público não me intimida.',
   'Speaking in public doesn''t intimidate me.',
   true, null),
  -- Immoderation (impulse control)
  ('bf_n_impl_1', 'big_five_120', 'big_five:facet:neuroticism:immoderation', 113,
   'Tenho dificuldade de resistir a tentações que sei que não me fazem bem.',
   'I struggle to resist temptations I know aren''t good for me.',
   false, null),
  ('bf_n_impl_2', 'big_five_120', 'big_five:facet:neuroticism:immoderation', 114,
   'Costumo me arrepender de coisas feitas no calor do momento.',
   'I often regret things I did in the heat of the moment.',
   false, null),
  ('bf_n_impl_3', 'big_five_120', 'big_five:facet:neuroticism:immoderation', 115,
   'Quando decido cortar algo, corto sem oscilar.',
   'When I decide to cut something out, I cut it cleanly.',
   true, null),
  ('bf_n_impl_4', 'big_five_120', 'big_five:facet:neuroticism:immoderation', 116,
   'Mantenho minhas vontades sob controle sem dificuldade.',
   'I keep my urges under control without trouble.',
   true, null),
  -- Vulnerability (panic under stress)
  ('bf_n_vuln_1', 'big_five_120', 'big_five:facet:neuroticism:vulnerability', 117,
   'Sob pressão alta eu travo ou desabo.',
   'Under high pressure I freeze or break down.',
   false, null),
  ('bf_n_vuln_2', 'big_five_120', 'big_five:facet:neuroticism:vulnerability', 118,
   'Crise me derruba — fico sem saber o que fazer.',
   'A crisis knocks me down — I don''t know what to do.',
   false, null),
  ('bf_n_vuln_3', 'big_five_120', 'big_five:facet:neuroticism:vulnerability', 119,
   'Em momentos de pressão, eu rendo melhor.',
   'I perform better under pressure.',
   true, null),
  ('bf_n_vuln_4', 'big_five_120', 'big_five:facet:neuroticism:vulnerability', 120,
   'Quando o caos chega, eu fico mais frio, não mais nervoso.',
   'When chaos arrives I get cooler, not more anxious.',
   true, null);

commit;
